### ISSUE TITLE
Documents are not sometimes listed when alternating between Metadata Management and Schema Management

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#20] opened 2023-05-11 08:50 UTC
**Describe the bug**

![image](https://github.com/kit-data-manager/frontend-collection/assets/88380730/e9c8b1e6-030b-4dc1-9ec4-69e26e974670)
Above: picture of blank document list  after clicking Schema Management and Metadata Management multiple times

While alternating between Metadata Management and Schema Management, the list of Documents disappear sometimes

Below: Picture after reloading the page.
![image](https://github.com/kit-data-manager/frontend-collection/assets/88380730/d42753eb-567e-4ccd-934f-8613a3efc057)

**To Reproduce**
1. Go to (https://matwerk.datamanager.kit.edu/metadata-management.html)
2. Click on Schema Management Tab
3. If you are lucky you will see the list of documents. Else reload to see the list of documents.
4. While alternating between Schema Management and Metadata Management multiple times, this behaviour can be reproduced.

**Expected behavior**
The list of documents should always be visible

**Screenshots**
are above

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser  Safari
 - Version 16.2

**Comment by ThomasJejkal** [comment] 2023-05-16 09:14
I cannot reproduce this issue. However, the MatWerk instance is using a rather old version of frontend-collection. As soon as I merged all recent changes, this instance should be updated and I would ask you to check again if this error still occurs for the new version.

**Comment by ThomasJejkal** [comment] 2023-07-27 12:22
I'll close this issue for now. Please re-open if the error still persists.

**Closed by ThomasJejkal** 2023-07-27 12:22 UTC
